apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil-ingress
  labels:
    app: wil-playground
spec:
  rules:
  - http:
      paths:
      - path: /wil
        pathType: Prefix
        backend:
          service:
             name: wil-service
             port:
                number: 80
